#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 20 17:51:22 2019

@author: alejandro
"""

import requests
import pandas as pd
import numpy as ny
from sklearn.linear_model import LinearRegression

"""Get Free API key at https://www.alphavantage.co/support/#api-key"""
"""Make sure you are entering correct stock symbol (Example: Apple = AAPL)"""
"""100 data point beta"""

a= input("Ticker?")
ab = input("API Key")

apiCall = requests.get("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol="+a+"&apikey="+ab)

def jsonprep(apiCall):
    jsonData = apiCall.json()
    cleanData = jsonData["Time Series (Daily)"]
    table = pd.DataFrame(cleanData)
    ttable = pd.DataFrame.transpose(table)
    return ttable

def dataprep(ttable):
    y = ny.array(ttable[ttable.columns[3]])
    y = y.astype(ny.float)
    y = y.astype(ny.int)
    y = pd.DataFrame(y).pct_change(1)
    y = ny.array(y[y.columns[0]])
    y = ny.delete(y,0)
    return y

y = dataprep(jsonprep(apiCall))


apiCallb = requests.get("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=^GSPC&apikey="+ab)

x = dataprep(jsonprep(apiCallb))
x = x.reshape(-1,1)


model = LinearRegression().fit(x, y)
print('Beta:', model.coef_)
