#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  8 02:23:59 2019

@author: alejandro
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  8 02:09:19 2019

@author: alejandro
"""

# -*- coding: utf-8 -*-

import requests
import pandas as pd
import statsmodels.api as sm
import numpy as ny


"""Get Free API key at https://www.alphavantage.co/support/#api-key"""
"""Make sure you are entering correct stock symbol (Example: Apple = AAPL)"""

symbol = input("Stock Symbol?")
a= "symbol="+symbol.upper()
api = input("API KEY?")

print (a)
def getDaily20():
    b = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&"+a+"&apikey="+api
    return b

apiCall = requests.get(getDaily20())
jsonData = apiCall.json()


cleanData = jsonData["Time Series (Daily)"]
table = pd.DataFrame(cleanData)
ttable = pd.DataFrame.transpose(table)

y = ny.array(ttable[ttable.columns[3]])
y = y.astype(ny.float)
y = y.astype(ny.int)

x = ny.array(range(1,len(y)+1))


x = sm.add_constant(x)
model = sm.OLS(y, x).fit() 
print_model = model.summary()
print(print_model)

fPrice = ((len(y)+1)*model.params[1])+model.params[0]

print("Stock should be: $"+str(int(fPrice)))
